export const COMMANDS = "commands";
export const MESSAGES_GET = "get messages";
export const MESSAGE_CREATE = "new message";
export const MESSAGE_DELETE = "message delete";
export const MESSAGE_UPDATE = "update message";
export const ROOM_INFORMATION = "rooms";
export const ROOM_LOGS = "room logs";
export const USER_INVENTORY_CHANGE = "invenory";
export const USER_NAME = "username";
